### PR TITLE
#13468 Display a combo dropdown with method and url

### PR DESCRIPTION
**Pull request by agreggio-slingr**
Pull-request for issue #13468 created by @agreggio-slingr

## What it does?

When selecting URL, display a combo dropdown with method and URL. For example:
GET /documents
GET /documents/{documentId}
POST /documents

## How to test it?

Config a new pandadoc-endpoint

Use pandadoc-endpoint and create an action with Action Type -> Flow

In the flow designer, create a new apiCall step and validate the dropdown contain verb + route, for example:
GET /download/{id}

Go to runtime and launch action

## Implementation notes

Need to create a new pandadoc tag

## Deployment notes

There are no deployment notes

### CODE REVIEW

**Comment by agreggio-slingr** [comment]
Screenshot from 2023-02-23 11-40-27
Screenshot from 2023-02-23 11-40-22

**Comment by sebasmoyano** [comment]
#approve

**Comment by pasaperez-work** [comment]
#approve

**Comment by pasaperez-work** [comment]
Last Tag created for implementation: v3.5.2

**Pull request merged**
